apiVersion: 'apps/v1'
kind: 'Deployment'
metadata:
  name: 'handbrake-job-file-mover'
  namespace: 'handbrake-jobs'
  labels:
    app: 'handbrake-job-file-mover'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 'handbrake-job-file-mover'
  template:
    metadata:
      labels:
        app: 'handbrake-job-file-mover'
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/metrics'
        prometheus.io/port: '8080'
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: 'kubernetes.io/hostname'
                    operator: 'NotIn'
                    values:
                      - 'k8smaster'
      containers:
        - name: 'handbrake-job-file-mover'
          image: 'chrisjohnson00/handbrake-file-mover:v2.5.1'
          imagePullPolicy: 'IfNotPresent'
          volumeMounts:
            - name: 'tv'
              mountPath: '/tv'
            - name: 'movies'
              mountPath: '/movies'
            - name: 'output'
              mountPath: '/output'
            - name: 'watch720p'
              mountPath: '/watch_720p'
            - name: 'watch1080p'
              mountPath: '/watch_1080p'
            - name: 'watch1080p-movies'
              mountPath: '/watch_1080p_movie'
          env:
            - name: 'output_directory_path'
              value: '/output'
            - name: 'move_tv_directory_path'
              value: '/tv'
            - name: 'move_movies_directory_path'
              value: '/movies'
            - name: 'CONSUL_HTTP_ADDR'
              value: 'consul-consul-server.consul:8500'
            - name: 'WATCH_720p'
              value: '/watch_720p'
            - name: 'WATCH_1080p'
              value: '/watch_1080p'
      volumes:
        - name: 'tv'
          nfs:
            server: '192.168.1.131'
            path: '/data/video/Television'
        - name: 'movies'
          nfs:
            server: '192.168.1.131'
            path: '/data/video/Movies'
        - name: 'output'
          nfs:
            server: '192.168.1.131'
            path: '/data/k8s/output'
        - name: 'watch720p'
          nfs:
            server: '192.168.1.131'
            path: '/data/k8s/watch_720p'
        - name: 'watch1080p'
          nfs:
            server: '192.168.1.131'
            path: '/data/k8s/watch_1080p_tv'
        - name: 'watch1080p-movies'
          nfs:
            server: '192.168.1.131'
            path: '/data/k8s/watch_1080p'
