language: bash
arch:
  - amd64
services:
  - docker
jobs:
  include:
    - stage: build branch
      script:
        - set -e
        - docker pull chrisjohnson00/handbrake-file-mover:main
        - docker build -t chrisjohnson00/handbrake-file-mover -f Dockerfile .
        - docker run chrisjohnson00/handbrake-file-mover python -m flake8
        - docker run chrisjohnson00/handbrake-file-mover python -m pytest
        - docker login --username=chrisjohnson00 --password=$DOCKER_HUB_PASSWORD
        - docker tag chrisjohnson00/handbrake-file-mover chrisjohnson00/handbrake-file-mover:$TRAVIS_BRANCH
        - docker push chrisjohnson00/handbrake-file-mover:$TRAVIS_BRANCH
      if: tag is blank
    - stage: build tag
      script:
        - docker build -t chrisjohnson00/handbrake-file-mover -f Dockerfile .
        - docker login --username=chrisjohnson00 --password=$DOCKER_HUB_PASSWORD
        - docker tag chrisjohnson00/handbrake-file-mover chrisjohnson00/handbrake-file-mover:$TRAVIS_TAG
        - docker push chrisjohnson00/handbrake-file-mover:$TRAVIS_TAG
        - docker push chrisjohnson00/handbrake-file-mover
      if: tag IS present
