image: python:3.8-slim
pipelines:
  default:
    - step:
        caches:
          - pip
          - docker
        script:
          - pip install -r requirements.txt
          - python -m pytest
          - docker login -u chrisjohnson00 -p $DOCKER_HUB_PASSWORD
          - docker build -t chrisjohnson00/handbrake-file-mover:$BITBUCKET_BRANCH .
          - docker push chrisjohnson00/handbrake-file-mover:$BITBUCKET_BRANCH
        services:
          - docker
  tags:
    '*':
      - step:
          caches:
            - pip
            - docker
          script:
            - docker login -u chrisjohnson00 -p $DOCKER_HUB_PASSWORD
            - docker build -t chrisjohnson00/handbrake-file-mover:latest .
            - docker tag chrisjohnson00/handbrake-file-mover:latest chrisjohnson00/handbrake-file-mover:$BITBUCKET_TAG
            - docker push chrisjohnson00/handbrake-file-mover:latest
            - docker push chrisjohnson00/handbrake-file-mover:$BITBUCKET_TAG
          services:
            - docker
